### ISSUE TITLE
Received FAILURE signal with UniqueId <Ec2_id>

### ISSUE THREAD

**Issue by Darktechie-programmer** [aws-samples/amazon-chime-pstn-audio-with-amazon-lex#235]
### Describe the bug

Hi there,

I have followed this document :
[add-conversational-ai-to-any-contact-center-with-amazon-lex-and-the-amazon-chime-sdk](https://aws.amazon.com/blogs/machine-learning/add-conversational-ai-to-any-contact-center-with-amazon-lex-and-the-amazon-chime-sdk/)

command Used:
1. git clone https://github.com/aws-samples/amazon-chime-pstn-audio-with-amazon-lex.git
2. cd amazon-chime-pstn-audio-with-amazon-lex
3. yarn    [Used for install the required package]
4. yarn launch

AWS :
Resion :-  us-west-2 (Oregon)

issue:
When I run command : **yarn launch**
It will give me **Received FAILURE signal with UniqueId i-0435dfdc4df866e84** error.

LexContactCenter | **81/84** | 12:11:54 pm | CREATE_FAILED        | AWS::EC2::Instance                    | Asterisk/Instance (AsteriskInstanceDB134462b913412e5ea193ab) Received FAILURE signal with UniqueId i-0435dfdc4df866e84

LexContactCenter | **81/84** | 12:11:55 pm | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | LexContactCenter The following resource(s) failed to create: [AsteriskInstanceDB134462b913412e5ea193ab]. Rollback requested by user.

Then it start rollback and delete all the created instances.

I have search the error and tried to solve but nothing worked for me.
Can you please guide me how I can solve this error.
Thanks

![issue1](https://user-images.githubusercontent.com/52384184/217172785-223fa0c3-2e80-4947-b678-f548ad54d73f.PNG)

### Expected behavior

After run the command :  yarn launch
it should provide the phone number details :

![ML-9155-image010](https://user-images.githubusercontent.com/52384184/217173064-2a0a99a1-a7de-41b5-bbef-0b89be60e080.jpg)

### Current behavior

When I run command : **yarn launch**
It will give me **Received FAILURE signal with UniqueId i-0435dfdc4df866e84** error.

![issue1](https://user-images.githubusercontent.com/52384184/217174302-d8d9fb0e-e3b0-46ba-bfe7-43e8e0228c45.PNG)

### Steps to Reproduce

command Used:
1. git clone https://github.com/aws-samples/amazon-chime-pstn-audio-with-amazon-lex.git
2. cd amazon-chime-pstn-audio-with-amazon-lex
3. yarn    [Used for install the required package]
4. yarn launch

### Possible Solution

I thing we need to changes the EC2 ID, I should be variable.

### Context

I'm trying to learn how the flow are working so I can create my contact center with Amazon Lex. 

### AWS SDK version used

aws-cli/2.9.10 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Operating System and version

OS: Window 10 pro, version: 21H2 (OS build 19044.2486)

**Comment by lapolonio** [comment]
When I ran the deploy it worked i'm on MacOS

**Comment by schuettc** [comment]
This should be resolved with: https://github.com/aws-samples/amazon-chime-pstn-audio-with-amazon-lex/pull/340

If the issue remains, please reopen.
